[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CTReconstruction"
authors = [{name = "Changrong Shi", email = "scr20@mails.tsinghua.edu.cn"}]
dynamic = ["version", "description"]
